-- POSTGREsql is CASE SENSITIVE**** BE aWaRe!, btw MySQL is not.

select * from thomas;
-- Q1-total revenue generated by male vs female customer

select gender, sum(purchase_amount) as revenue from thomas
group by gender;
-- Q2- which customers used a discount coupon and still spent more than avg purchase amount?

select customer_id, purchase_amount from thomas
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from thomas);


-- NOTE- i can also write "where discount_applied ILIKE 'Yes' ", ILIKE removes case sensitvity from that query 

--Q3- top 5 products with highest avg review_rating?

select  item_purchased, avg(review_rating) from thomas 
group by item_purchased
order by avg (review_rating) desc
limit 5;


--OR


select  item_purchased, round(avg(review_rating)::numeric,2) from thomas 
group by item_purchased
order by avg (review_rating) desc
limit 5;



-- this is wrong query-)
-- (above is correct one)                         -- select item_purchased,review_rating
                                                                  -- from thomas
                                                   -- order by review_rating desc
                                                                      -- limit 5;

--Q4 which 5 products have highest %tage of purchases with discounts applied?

select item_purchased, sum(case when discount_applied = 'Yes' then 1 else 
                         0 END)* 100 /count(*) as discount_rate from thomas
						 group by item_purchased
						 order by discount_rate desc
						 limit 5;

-- SELECT column_name, data_type
-- FROM information_schema.columns                             #tells datatype of column
-- WHERE table_name = 'thomas'
--   AND column_name = 'discount_applied';


SELECT discount_applied, COUNT(*)
FROM thomas
GROUP BY discount_applied;                     

         -- OR
		 
select discount_applied, count(discount_applied) from thomas
group by discount_applied;                        --
                                                      

-- -- note- ) -                COUNT() counts rows.
--                             COUNT(column) counts non-NULL values.
--                             Use COUNT() by default.
--                             Use COUNT(column) only when you want to exclude NULLs.


SELECT
  item_purchased,
  SUM(CASE WHEN TRIM(discount_applied) = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS discount_rate
FROM thomas
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


SELECT DISTINCT discount_applied, LENGTH(discount_applied)
FROM thomas;

               -- OR
SELECT discount_applied, LENGTH(discount_applied)
FROM thomas
group by discount_applied;

--segment customers into new,returning and loyal based on their total no. of previous 
-- purchases and show the count of each.       #its customers segmentation ques, IMP!

-- select max(previous_purchases),min(previous_purchases) from thomas;
-- select (previous_purchases) from thomas;







SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM thomas
GROUP BY customer_segment;


--                           OR



-- 

WITH customer_loyalty as (
Select customer_id, previous_purchases, 
Case
    when previous_purchases =1 THEN 'New'
	when previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
else 'Loyal'
end as customer_type
from thomas
)
select customer_type ,count(*)
from customer_loyalty
group by customer_type;

--Q - TOP 3 most purchased products within each category?

select category, item_purchased , count(*) as purchase_count
from thomas
group by item_purchased,category
order by purchase_count,category desc ;          --#This query gave all(all cateories and
                                                 -- and their purchases total,but we wanted a 
 												 --winner(top product) in each category))
-- SO we  NEED WINDOWS FUNCTION TO RANK PRODUCTS HERE!








SELECT category,item_purchased, COUNT(*)
FROM thomas
GROUP BY category,item_purchased;
-- etc etc...

-- Que- are customers who r repeat buyers(more than 5 previous purchases) also 
-- likely to subscribe
-- how to approach this ques- Among customers with previous_purchases > 5,
-- how many subscribed?
-- This is a relationship question.


select subscription_status,
count(customer_id) as repeat_buyers
from thomas
where previous_purchases > 5
group by subscription_status;  (#if want yes and no row section)



-- #above query answers -“How many repeat buyers subscribed?”


-- Q- revenue contribution of each age-group?
select age_group, sum(purchase_amount) as revenue
from thomas
group by age_group
order by revenue desc;



